vine_to_color = {
    'Cabernet Sauvignon': 'red',
    'Syrah': 'red',
    'Pinot Noir': 'red',
    'Merlot': 'red',
    'Tempranillo': 'red',
    'Sangiovese': 'red',
    'Grenache': 'red',
    'Barbera': 'red',
    'Cabernet Franc': 'red',
    'Malbec': 'red',
    'Chardonnay': 'white',
    'Sauvignon Blanc': 'white',
    'Riesling': 'white',
    'Muskat': 'white',
    'Pinot Gris': 'white',
    'Chenin Blanc': 'white',
    'Albariño': 'Latin white',
    'Gewürztraminer': 'white',
    'Viognier': 'white',
    'Fiano': 'white',
}

country_to_continent = {
        'Italy': 'Europe',
        'Portugal': 'Europe',
        'US': 'North America',
        'Spain': 'Europe',
        'France': 'Europe',
        'Germany': 'Europe',
        'Argentina': 'Latin America',
        'Chile': 'Latin America',
        'Australia': 'Oceania',
        'Austria': 'Europe',
        'South Africa': 'Africa',
        'New Zealand': 'Oceania',
        'Israel': 'Asia',
        'Hungary': 'Europe',
        'Greece': 'Europe',
        'Romania': 'Europe',
        'Mexico': 'Latin America',
        'Canada': 'North America',
        'Turkey': 'Asia',
        'Czech Republic': 'Europe',
        'Slovenia': 'Europe',
        'Luxembourg': 'Europe',
        'Croatia': 'Europe',
        'Georgia': 'Europe',
        'Uruguay': 'Latin America',
        'England': 'Europe',
        'Lebanon': 'Asia',
        'Serbia': 'Europe',
        'Brazil': 'Latin America',
        'Moldova': 'Europe',
        'Morocco': 'Africa',
        'Peru': 'Latin America',
        'India': 'Asia',
        'Bulgaria': 'Europe',
        'Cyprus': 'Europe',
        'Armenia': 'Asia',
        'Switzerland': 'Europe',
        'Bosnia and Herzegovina': 'Europe',
        'Ukraine': 'Europe',
        'Slovakia': 'Europe',
        'Macedonia': 'Europe',
        'China': 'Asia',
        'Egypt': 'Africa',
        'Albania': 'Europe',
        'Lithuania': 'Europe',
        'Japan': 'Asia',
        'South Korea': 'Asia',
        'Montenegro': 'Europe',
        'Tunisia': 'Africa',
        'US-France': 'Europe',
    }